
ECoG Stats Report
========================================================

This report uses linear mixed effects models to evaluate the statistical validity 
of the data. 

Data details:
```{r}
lockType = "stim"
type = "power"
band = "hgam"
```

Additional setup:
-------------------------------------------------------
Load necessary libraries:
```{r}
library('lme4');
library('pbkrtest');
```

Set additional variables:
```{r}
dataPath = '~/Documents/ECOG/Results/Rdata/';
hem 		= 'all';
ref 		= 'nonLPCleasL1TvalCh10';
binType     = 'Bin';
byBlockStr 	= 'bySubj';

if (lockType == 'stim'){
	timeStr 	= '0msTo1000ms'
}else if (lockType == 'RT'){
	timeStr 	= 'n1000msTo200ms'
	}	

if (type=='erp'){  
  band 			= '';
  preFix 		= paste(binType,timeStr,hem,'ERPs',sep='')
  baseLine 		= 'sub';
  analysisType 	= 'Amp';
}else if (type=='power'){
  preFix 		= paste(binType,timeStr,hem,'ERSPs',band,sep='')
  baseLine 		= 'sub';
  analysisType 	= 'logPower';
}

fileName = paste(preFix,'Group',lockType,'Lock',baseLine,analysisType,ref,byBlockStr,sep='');
```

Load data:
```{r}
data 		<- read.csv(paste(dataPath,fileName,'.csv',sep=''),header=F)
names(data) <- c('M','blank1','T','blank2','Z','blank3','BinNum','chanId','subjId', 'blockId', 
				 'ROI','dP','HR','FAR','hem','subROI','ITC_Z','ITP_Z',
				 'Zc','ZcH','ZcCRs','ZH','ZCRs')

data$BinNum 		= as.factor(data$BinNum)
data$chanId 		= as.factor(data$chanId)
data$subjId  		= as.factor(data$subjId)
data$blockId  		= as.factor(data$blockId)
data$ROI  			= as.factor(data$ROI);
levels(data$ROI)	= c('IPS','SPL','AG')
data$chanId 		= as.factor(data$chanId)
data$hem 			= as.factor(data$hem);
levels(data$hem)	= c('left','right')
data$subROI  		= as.factor(data$subROI);
levels(data$subROI) = c('','pIPS','aIPS','pSPL','aSPL')

nBins 	= length(unique(data$BinNum));
nChans 	= length(unique(data$chanId));
nSubjs 	= length(unique(data$subjId));
nBlocks = length(unique(data$blockId));
nROIs 	= length(unique(data$ROI));
```

LMER models, evaluated with Kenward-Roger approximation Ftests 
------------------------------------------------
**For the lefts subjects: IPS, SPL interaction test**
```{r}
subL 			= (data$hem=='left') & (data$ROI=='IPS' | data$ROI=='SPL')
fullModel 	    = lmer(Z ~ 1 + ROI*BinNum + (1|subjId) + (BinNum|subjId) + (ROI|subjId) + (1|chanId),data=data,subset=subL,REML=F);
Model_BinNum_ROI= lmer(Z ~ 1 + ROI+BinNum + (1|subjId) + (BinNum|subjId) + (ROI|subjId) + (1|chanId),data=data,subset=subL,REML=F);
anova(fullModel,Model_BinNum_ROI)
KRmodcomp(fullModel,Model_BinNum_ROI)
```
**IPS omnibus time test**
```{r}
subL 			= (data$hem=='left') & (data$ROI=='IPS')
fullModel 		= lmer(Z ~ 1 + BinNum + (1|subjId) + (1|chanId),data=data,subset=subL,REML=F);
Model_BinNum 	= lmer(Z ~ 1 + (1|subjId) + (1|chanId),data=data,subset=subL,REML=F);
anova(fullModel,Model_BinNum)
KRmodcomp(fullModel,Model_BinNum)
```
**SPL omnibus time test**
```{r}
subL 			= (data$hem=='left') & (data$ROI=='SPL')
fullModel 		= lmer(Z ~ 1 + BinNum + (1|subjId) + (1|chanId),data=data,subset=subL,REML=F);
Model_BinNum 	= lmer(Z ~ 1 + (1|subjId) + (1|chanId),data=data,subset=subL,REML=F);
anova(fullModel,Model_BinNum)
KRmodcomp(fullModel,Model_BinNum)
```
